# Generated by Django 6.0.6 on 2026-06-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.CharField(max_length=255)),
                ('drop', models.CharField(max_length=255)),
                ('demand', models.IntegerField()),
                ('supply', models.IntegerField()),
                ('time_of_day', models.CharField(max_length=50)),
                ('traffic_level', models.CharField(max_length=50)),
                ('weather', models.CharField(max_length=50)),
                ('predicted_price', models.FloatField(blank=True, null=True)),
                ('surge_multiplier', models.FloatField(blank=True, null=True)),
                ('base_price', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
